<?php
/**
 * Created by PhpStorm.
 * User: yuanxx
 * Date: 2018/3/30
 * Time: 11:57
 */

namespace app\common\controller;


use think\Controller;

class CommonController extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub


    }


}